// flatbuffer-tcp.cpp : This file contains the 'main' function. Program execution begins and ends there.
/*
C++ Development Assignment

Research on the Google FlatBuffers projects (https://google.github.io/flatbuffers/) and work on following tasks:

Write a sample schema that can represent a property tree (property name, property value, property type, and sub-properties).

Write code snippets in C++ that can read/update on the property object generated by the FlatBuffers compiler.

Write code snippets in C++ that can send/receive the property object over TCP socket.

Write code snippets in C++ that use the reflection API to read from the TCP socket and iterate over the elements stored inside the property tree.

Consider the property tree will be updated frequently by the sender, think of a solution that synchronize the updates to the receiver.

*/

#include <iostream>

int main()
{
    std::cout << "Hello World!\n";
}

// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu

// Tips for Getting Started: 
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file
